AWSTemplateFormatVersion: 2010-09-09

Description: Udagram Infrastructure

Parameters:

  EnvironmentName:
    Description: Name of the environment
    Type: String
    Default: Udagram


Resources:

  # ---------------------------------
  # LOAD BALANCER SECURITY GROUP
  # ---------------------------------

  LBSecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:

      GroupDescription: Allow HTTP from Internet

      VpcId:
        Fn::ImportValue: !Sub "${EnvironmentName}-VPCID"

      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0


  # ---------------------------------
  # WEB SERVER SECURITY GROUP
  # ---------------------------------

  WebServerSecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:

      GroupDescription: Allow HTTP from Load Balancer

      VpcId:
        Fn::ImportValue: !Sub "${EnvironmentName}-VPCID"

      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          SourceSecurityGroupId: !Ref LBSecGroup

      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0


  # ---------------------------------
  # LAUNCH TEMPLATE
  # ---------------------------------

  WebAppLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:

      LaunchTemplateName: !Sub "${EnvironmentName}-lt"

      LaunchTemplateData:

        ImageId: ami-0557a15b87f6559cf

        InstanceType: t2.micro

        SecurityGroupIds:
          - !Ref WebServerSecGroup

        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            yum update -y
            yum install httpd -y
            systemctl start httpd
            systemctl enable httpd
            echo "Udagram Project Working!" > /var/www/html/index.html


  # ---------------------------------
  # TARGET GROUP
  # ---------------------------------

  WebAppTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:

      Port: 80

      Protocol: HTTP

      VpcId:
        Fn::ImportValue: !Sub "${EnvironmentName}-VPCID"

      HealthCheckPath: /

      HealthCheckProtocol: HTTP

      TargetType: instance


  # ---------------------------------
  # LOAD BALANCER
  # ---------------------------------

  WebAppLB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:

      Scheme: internet-facing

      Type: application

      Subnets:
        - Fn::ImportValue: !Sub "${EnvironmentName}-PUB1-SN"
        - Fn::ImportValue: !Sub "${EnvironmentName}-PUB2-SN"

      SecurityGroups:
        - !Ref LBSecGroup


  # ---------------------------------
  # LISTENER
  # ---------------------------------

  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:

      LoadBalancerArn: !Ref WebAppLB

      Port: 80

      Protocol: HTTP

      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref WebAppTargetGroup


  # ---------------------------------
  # AUTO SCALING GROUP
  # ---------------------------------

  WebAppGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:

      VPCZoneIdentifier:
        Fn::Split:
          - ","
          - Fn::ImportValue: !Sub "${EnvironmentName}-PRIV-NETS"

      LaunchTemplate:
        LaunchTemplateId: !Ref WebAppLaunchTemplate
        Version: !GetAtt WebAppLaunchTemplate.LatestVersionNumber

      MinSize: "1"

      MaxSize: "2"

      DesiredCapacity: "1"

      TargetGroupARNs:
        - !Ref WebAppTargetGroup


Outputs:

  LoadBalancerDNS:
    Description: Load Balancer DNS Name

    Value: !GetAtt WebAppLB.DNSName
